### ISSUE TITLE
Время не редактируется после срабатывания таймера

### ISSUE THREAD

**Issue by Mogby** [Mogby/lofitimer#15]
Что происходит:
 - Запускаем таймер на 1 секунду
 - Он срабатывает
 - Пытаемся поставить другое время
 - Ничего не выходит
 - Плак-плак

Что должно происходить:
 - Запускаем таймер на 1 секунду
 - Он срабатывает
 - Пытаемся поставить другое время
 - Время на таймере меняется

**Comment by alexandr3307** [comment]
В случае если таймер заканчивает отсчет, нельзя будет выбрать другое время. Нужно при окончании отсчета очистить стейт

**Comment by Mogby** [comment]
Привязал включение/отключение редактирования к событиям таймера: [раз](https://github.com/Mogby/lofitimer/pull/19/files#diff-6a0c96bc9a00f5a43d06339bf35a7512a437a3d3b3edc6d358fd3ed8d3204396R13), [два](https://github.com/Mogby/lofitimer/pull/19/files#diff-6a0c96bc9a00f5a43d06339bf35a7512a437a3d3b3edc6d358fd3ed8d3204396R20), [три](https://github.com/Mogby/lofitimer/pull/19/files#diff-6a0c96bc9a00f5a43d06339bf35a7512a437a3d3b3edc6d358fd3ed8d3204396R29). Бага ушла и по идее не должна вернуться, если таймер не перестанет вовремя тригерить ивенты.
